bind-address = "0.0.0.0"

[initialization]
join-urls = "" # Comma-delimited URLs, in the form http://host:port, for joining another cluster.

[authentication]
enabled = false

[logging]
file   = "/opt/influxdb/shared/data/influxdb.log"

[admin]
enabled = true
port = 8083

[api]
port = 8086

[[graphite]]
enabled = true
port = 2004
protocol = "tcp"
database = "graphite"

[broker]
dir  = "/opt/influxdb/data/raft"
port = 8086

[data]
  dir = "/opt/influxdb/data/db"
  port = 8086

  # Control whether retention policies are enforced and how long the system waits between
  # enforcing those policies.
  retention-check-enabled = true
  retention-check-period = "10m"

[cluster]
dir = "/opt/influxdb/data/state"

