#! /bin/bash

docker kill influxdb09
docker rm influxdb09

docker run -d \
	-p 9083:8083 \
  -p 9086:8086 \
  -p 9004:2004 \
  -v /var/docker/influxdb09:/opt/influxdb/shared/data \
  --name influxdb09 torkelo/influxdb09
